/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppApplicationsIndexRouteImport } from './routes/_app.applications.index'
import { Route as AppApplicationsIdRouteImport } from './routes/_app.applications.$id'
import { Route as AppLogsIndexRouteImport } from './routes/_app.logs.index'
import { Route as AppLogsIdRouteImport } from './routes/_app.logs.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsIndexRoute = AppApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsIdRoute = AppApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsIndexRoute = AppLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsIdRoute = AppLogsIdRouteImport.update({
  id: '/logs/$id',
  path: '/logs/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/applications/$id': typeof AppApplicationsIdRoute
  '/logs/$id': typeof AppLogsIdRoute
  '/applications/': typeof AppApplicationsIndexRoute
  '/logs/': typeof AppLogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/applications/$id': typeof AppApplicationsIdRoute
  '/logs/$id': typeof AppLogsIdRoute
  '/applications': typeof AppApplicationsIndexRoute
  '/logs': typeof AppLogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/applications/$id': typeof AppApplicationsIdRoute
  '/_app/logs/$id': typeof AppLogsIdRoute
  '/_app/applications/': typeof AppApplicationsIndexRoute
  '/_app/logs/': typeof AppLogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications/$id'
    | '/logs/$id'
    | '/applications/'
    | '/logs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/applications/$id' | '/logs/$id' | '/applications' | '/logs'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/applications/$id'
    | '/_app/logs/$id'
    | '/_app/applications/'
    | '/_app/logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications/': {
      id: '/_app/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AppApplicationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications/$id': {
      id: '/_app/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AppApplicationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs/': {
      id: '/_app/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AppLogsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs/$id': {
      id: '/_app/logs/$id'
      path: '/logs/$id'
      fullPath: '/logs/$id'
      preLoaderRoute: typeof AppLogsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppApplicationsIdRoute: typeof AppApplicationsIdRoute
  AppLogsIdRoute: typeof AppLogsIdRoute
  AppApplicationsIndexRoute: typeof AppApplicationsIndexRoute
  AppLogsIndexRoute: typeof AppLogsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppApplicationsIdRoute: AppApplicationsIdRoute,
  AppLogsIdRoute: AppLogsIdRoute,
  AppApplicationsIndexRoute: AppApplicationsIndexRoute,
  AppLogsIndexRoute: AppLogsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
