services:
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - tracevault
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tracevault
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    networks:
      - tracevault

networks:
  tracevault:
    driver: bridge

volumes:
  postgres_data: